version: '3.8'

volumes:
  service_postgres_data:

services:
  front:
    container_name: front
    image: measuresoftgram-front:latest
    restart: on-failure
    build:
      context: .
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/
